### ISSUE TITLE
Nicely Bulma?

### ISSUE THREAD

**Issue by cympfh** [himkt/frontend-template#7]
https://github.com/cympfh/nyo/commit/042ecfc57ade605ae4181a26976051c21ebc0112

I don't know how to PR to template repository.

**Comment by himkt** [comment]
I picked your commit. Thank you.
https://github.com/himkt/frontend-template/commit/3698f30faf2cab38e38d16fd9f3d203451ecb035

I think you create a repository based on himkt/frontend-tempalte (not forked it).
After forking the repository, it would be possible to open a PR.

**Comment by cympfh** [comment]
😃
